sudo: required
dist: trusty

language: node_js

node_js:
  - stable

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - unset _JAVA_OPTIONS
  - npm test
